export const productsData = [
    {
        handle: 'bedside-table',
        title: 'Bedside Table',
        body: '<p>Wooden bedside table</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Indoor',
        tags: ['Bedroom', 'Wood'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 69.99,
        compare_at_price: 85,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/dark-wall-bedside-table_925x_4353a689-6a4e-4f9a-8e07-976f20d1392a.jpg?v=1692687998',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 0,
        country_origin: '',
    },
    {
        handle: 'black-bean-bag',
        title: 'Black Beanbag',
        body: '<p>Black leather beanbag</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Indoor',
        tags: ['Black', 'Leather'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 6,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 69.99,
        compare_at_price: 80,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/comfortable-living-room-cat_925x_880111c1-6ed8-45bc-bbe7-0df0c1958b8b.jpg?v=1692687997',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 1,
        country_origin: '',
    },
    {
        handle: 'vanilla-candle',
        title: 'Vanilla candle',
        body: '<p>Vanilla scent candle in jar</p>',
        vendor: 'Home Sweet Home',
        product_category: '',
        type: 'Indoor',
        tags: ['Candle'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: true,
        inventory_qty: 5,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 15.99,
        compare_at_price: 30,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/diy-organic-candle_925x_383aad38-d99c-4ede-a26f-48c0b6774927.jpg?v=1692687995',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 2,
        country_origin: '',
    },
    {
        handle: 'knitted-throw-pillows',
        title: 'Knitted Throw Pillows',
        body: '<p>Homemade knitted throw pillows in a variety of colors</p>',
        vendor: 'Home Sweet Home',
        product_category: '',
        type: 'Indoor',
        tags: ['Pillows'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 19.99,
        compare_at_price: 25.99,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/yellow-sofa-with-throw-pillows_925x_bb2e3824-9109-47eb-81fa-c77fec1626c6.jpg?v=1692687994',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 3,
        country_origin: '',
    },
    {
        handle: 'yellow-sofa',
        title: 'Yellow Sofa',
        body: '<p>Two seater yellow sofa with wooden legs</p>',
        vendor: 'Home Sweet Home',
        product_category: '',
        type: 'Indoor',
        tags: ['Sofa'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 5,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 99.99,
        compare_at_price: 150,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/yellow-couch-by-black-and-white-mural_925x_cd7e5326-aeb6-49c7-895d-3da7024396d9.jpg?v=1692687992',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 4,
        country_origin: '',
    },
    {
        handle: 'wooden-fence',
        title: 'Wooden Fence',
        body: '<p>Wooden garden fence</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Outdoor',
        tags: ['Garden', 'Wood'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: true,
        inventory_qty: 5,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 200,
        compare_at_price: 300,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/picket-fence-flowers_925x_87954d90-1a9a-4237-992a-c025e9aebf42.jpg?v=1692687991',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 5,
        country_origin: '',
    },
    {
        handle: 'wooden-outdoor-slats',
        title: 'Wooden outdoor slats',
        body: '<p>Wooden outdoor fencing slats</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Outdoor',
        tags: ['Garden', 'Wood'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 0,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 25.99,
        compare_at_price: 35,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/house-plant-on-wooden-slat-wall_925x_b6b63cab-b10c-47fb-a126-6ca2480d4a32.jpg?v=1692687989',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 6,
        country_origin: '',
    },
    {
        handle: 'grey-sofa',
        title: 'Grey Sofa',
        body: '<p>Large four seater grey sofa</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Indoor',
        tags: ['Sofa'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 6,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 29.99,
        compare_at_price: 35,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/large-grey-sofa-by-brick-wall_925x_d00e864c-c607-4ad4-8ae8-7b8b778ac315.jpg?v=1692687988',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 7,
        country_origin: '',
    },
    {
        handle: 'biodegradable-cardboard-pots',
        title: 'Biodegradable cardboard pots',
        body: '<p>Biodegradable outdoor cardboard pots</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Outdoor',
        tags: ['Garden', 'Plants'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: true,
        inventory_qty: 8,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 10,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/potted-seeds_925x_b00ad0c4-9eba-4ae6-9709-eed7592339fc.jpg?v=1692687986',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 8,
        country_origin: '',
    },
    {
        handle: 'gardening-hand-trowel',
        title: 'Gardening hand trowel',
        body: '<p>Metal gardening hand trowel with wooden handle</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Outdoor',
        tags: ['Plants'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 2,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 10.99,
        compare_at_price: 25,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/spring-gardening-set-up_925x_45133040-8001-4dc8-8ff8-fd009bd014b8.jpg?v=1692687985',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 9,
        country_origin: '',
    },
    {
        handle: 'yellow-watering-can',
        title: 'Yellow watering can',
        body: '<p>Vintage vibrant watering can</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Outdoor',
        tags: ['Plants'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 4,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 40.99,
        compare_at_price: 50,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/flowers-in-yellow-watering-can_925x_db728864-6da6-46f9-bd4c-7a5420aa6b97.jpg?v=1692687983',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 10,
        country_origin: '',
    },
    {
        handle: 'white-ceramic-pot',
        title: 'White Ceramic Pot',
        body: '<p>Homemade white ceramic flower pot</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Indoor',
        tags: ['Plants', 'Pot'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: true,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 15.99,
        compare_at_price: 30,
        requires_shipping: true,
        is_taxable: true,
        barcode: 'sdhhjt',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/house-plant-in-white-pot_925x_19d1c012-cb70-47bd-aa41-5747abf234e0.jpg?v=1692687982',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 11,
        country_origin: '',
    },
    {
        handle: 'brown-throw-pillows',
        title: 'Brown Throw Pillows',
        body: '<p>Stylish brown throw pillows</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Indoor',
        tags: ['Pillows'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 5,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 19.99,
        compare_at_price: 25.99,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/bedroom-bed-with-brown-throw-pillows_925x_b911bbf4-c9df-4b44-88ef-7ba7410ab4c8.jpg?v=1692687980',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 12,
        country_origin: '',
    },
    {
        handle: 'wooden-outdoor-table',
        title: 'Wooden Outdoor Table',
        body: '<p>Chic wooden outdoor garden table</p>',
        vendor: 'Rustic LTD',
        product_category: '',
        type: 'Outdoor',
        tags: ['Garden', 'Wood'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 3,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 99.99,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/cafe-patio_925x_92c895cf-95c5-4106-9efb-eeef0e6c187a.jpg?v=1692687979',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 13,
        country_origin: '',
    },
    {
        handle: 'pink-armchair',
        title: 'Pink Armchair',
        body: '<p>Stylish pink armchair</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Indoor',
        tags: ['Chair'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 0,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 750,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/soft-pink-cushioned-armchair-in-stately-salon_925x_c8a8478c-f396-4aac-b74b-9596ab9a8fd9.jpg?v=1692687977',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 14,
        country_origin: '',
    },
    {
        handle: 'white-bed-clothes',
        title: 'White Bed Clothes',
        body: '<p>Sleek white bed clothes</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Indoor',
        tags: ['Bed'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: true,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 29.99,
        compare_at_price: 35,
        requires_shipping: true,
        is_taxable: true,
        barcode: 'vdfsrth',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/bright-hotel-room-bed_925x_779b4cc7-6ddd-480a-8ac0-57252d41e8ac.jpg?v=1692687976',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 15,
        country_origin: '',
    },
    {
        handle: 'antique-drawers',
        title: 'Antique Drawers',
        body: '<p>Antique wooden chest of drawers</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Indoor',
        tags: ['Antique', 'Bedroom'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 2,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 250,
        compare_at_price: 300,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/babys-room_925x_69cb39f7-4079-406a-87b1-04cec24867df.jpg?v=1692687974',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 16,
        country_origin: '',
    },
    {
        handle: 'cream-sofa',
        title: 'Cream Sofa',
        body: '<p>Comfortable cream sofa with wooden base</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Indoor',
        tags: ['Couch', 'Wood'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 4,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 500,
        compare_at_price: 750,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/condominium-interior-livingroom_925x_2c3fec8d-383d-4f0b-acac-c5da5d6a3f84.jpg?v=1692687973',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 17,
        country_origin: '',
    },
    {
        handle: 'copper-light',
        title: 'Copper Light',
        body: '<p>Stylish copper bedside light</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Indoor',
        tags: ['Bedroom', 'Copper'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 2,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 59.99,
        compare_at_price: 75,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/copper-light-in-bedroom_925x_e624a881-d661-4d15-8491-62f9eee91bd1.jpg?v=1692687971',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 18,
        country_origin: '',
    },
    {
        handle: 'clay-plant-pot',
        title: 'Clay Plant Pot',
        body: '<p>Classic blown clay pot for plants</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Outdoor',
        tags: ['Plants', 'Pot'],
        published: true,
        variant_title: 'Size',
        'Option1 Value': 'Regular',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 9.99,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/single-sprout-in-a-pot_925x_145fd7e4-59da-4daa-9eb4-3fb78c7ba8ab.jpg?v=1692687969',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 19,
        country_origin: '',
    },
    {
        handle: 'clay-plant-pot',
        title: '',
        body: '',
        vendor: '',
        product_category: '',
        type: '',
        tags: [],
        published: true,
        'Option 1 Name': 'Size',
        variant_title: 'Regular',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 9.99,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/single-sprout-in-a-pot_925x_145fd7e4-59da-4daa-9eb4-3fb78c7ba8ab.jpg?v=1692687969',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 20,
        country_origin: '',
    },
    {
        handle: 'clay-plant-pot',
        title: '',
        body: '',
        vendor: '',
        product_category: '',
        type: '',
        tags: [],
        published: '',
        'Option1 Name': '',
        'variant_title': 'Large',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 3,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 15.99,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/pot-with-a-single-sprout_925x_d47a2855-67db-4267-be21-91295b80ec06.jpg?v=1692687969',
        'Image Position': 2,
        'Image Alt Text': '',
        'Gift Card': '',
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: '',
        included_international: '',
        status: '',
        id: 21,
        country_origin: '',
    },
    {
        handle: 'led-high-tops',
        title: 'LED High Tops',
        body: '<p>Black high top shoes with green LED lights in the sole, tied up with laces and a buckle.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['men'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 80,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/putting-on-your-shoes_925x_53fd5901-603f-46cd-ae7e-749fde614d3c.jpg?v=1692687796',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 22,
        country_origin: '',
    },
    {
        handle: 'striped-skirt-and-top',
        title: 'Striped Skirt and Top',
        body: '<p>Black cotton top with matching striped skirt.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: true,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 50,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/woman-in-the-city_925x_9eeddbd3-cc72-4a00-9e22-d971c73c6ff8.jpg?v=1692687795',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 23,
        country_origin: '',
    },
    {
        handle: 'red-sports-tee',
        title: 'Red Sports Tee',
        body: "<p>Women's red sporty t-shirt with colorful details on the sleeves and a small white pocket.</p>",
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 50,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/womens-red-t-shirt_925x_f96ea48b-f06c-4f19-8a9e-fa3fc6a523b6.jpg?v=1692687793',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 24,
        country_origin: '',
    },
    {
        handle: 'blue-silk-tuxedo',
        title: 'Blue Silk Tuxedo',
        body: '<p>Blue silk tuxedo with marbled aquatic pattern and dark lining. Sleeves are complete with rounded hem and black buttons.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['men'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 70,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/man-adjusts-blue-tuxedo-bowtie_925x_dc38eb0a-d094-442a-9063-ea1c78e7edb5.jpg?v=1692687792',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 25,
        country_origin: '',
    },
    {
        handle: 'olive-green-jacket',
        title: 'Olive Green Jacket',
        body: '<p>Loose fitting olive green jacket with buttons and large pockets. Multicoloured pattern on the front of the shoulders.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 65,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/urban-fashion_925x_19f5df54-adde-4a8b-b6ba-04fd2f3e1a51.jpg?v=1692687790',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 26,
        country_origin: '',
    },
    {
        handle: 'white-cotton-shirt',
        title: 'White Cotton Shirt',
        body: '<p>Plain white cotton long sleeved shirt with loose collar. Small buttons and front pocket.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: true,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 30,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/smiling-woman-poses_925x_0d7caff0-3448-44e6-91c2-98e0cde01beb.jpg?v=1692687788',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 27,
        country_origin: '',
    },
    {
        handle: 'chequered-red-shirt',
        title: 'Chequered Red Shirt',
        body: '<p>Classic mens plaid flannel shirt with long sleeves, in chequered style, with two chest pockets.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['men'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 50,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/red-plaid-shirt_925x_e85faa2d-61df-432e-9f77-5fd4df54a43c.jpg?v=1692687787',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 28,
        country_origin: '',
    },
    {
        handle: 'longsleeve-cotton-top',
        title: 'Long Sleeve Cotton Top',
        body: '<p>Black cotton womens top, with long sleeves, no collar and a thick hem.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 50,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/woman-outside-brownstone_925x_3d3baa23-706e-4b9f-8798-48f712b6c778.jpg?v=1692687785',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 29,
        country_origin: '',
    },
    {
        handle: 'silk-summer-top',
        title: 'Silk Summer Top',
        body: '<p>Silk womens top with short sleeves and number pattern.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 70,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/young-hip-woman-at-carnival_925x_465d8c62-d613-46cd-a3d1-080a58ddb569.jpg?v=1692687783',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 30,
        country_origin: '',
    },
    {
        handle: 'zipped-jacket',
        title: 'Zipped Jacket',
        body: "<p>Dark navy and light blue men's zipped waterproof jacket with an outer zipped chestpocket for easy storeage.</p>",
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['men'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 65,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/menswear-blue-zip-up-jacket_925x_d4152430-413a-4222-b7dc-1e5dc402177e.jpg?v=1692687782',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 31,
        country_origin: '',
    },
    {
        handle: 'black-leather-bag',
        title: 'Black Leather Bag',
        body: '<p>Womens black leather bag, with ample space. Can be worn over the shoulder, or remove straps to carry in your hand.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 30,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/black-bag-over-the-shoulder_925x_b000a82a-20b1-4958-90e4-31446f8ea747.jpg?v=1692687780',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 32,
        country_origin: '',
    },
    {
        handle: 'dark-winter-jacket',
        title: 'Soft Winter Jacket',
        body: '<p>Thick black winter jacket, with soft fleece lining. Perfect for those cold weather days.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 50,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/smiling-woman-on-snowy-afternoon_925x_2d20cc36-2614-4984-bd32-24759a54c926.jpg?v=1692687778',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 33,
        country_origin: '',
    },
    {
        handle: 'navy-sport-jacket',
        title: 'Navy Sports Jacket',
        body: "<p>Long-sleeved navy waterproof jacket in thin, polyester fabric with a soft mesh inside. The durable water-repellent finish means you'll be kept comfortable and protected when out in all weathers.</p>",
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['men'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 60,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/mens-fall-fashion-jacket_925x_0bc3ae15-84e0-4cde-90e3-f6e1ee97b394.jpg?v=1692687777',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 34,
        country_origin: '',
    },
    {
        handle: 'dark-denim-top',
        title: 'Dark Denim Top',
        body: '<p>Classic dark denim top with chest pockets, long sleeves with buttoned cuffs, and a ripped hem effect.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 60,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/young-female-models-denim_925x_108f1e5f-e5e0-406d-b8e8-39f0523ea5d8.jpg?v=1692687775',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 35,
        country_origin: '',
    },
    {
        handle: 'classic-leather-jacket',
        title: 'Classic Leather Jacket',
        body: '<p>Womans zipped leather jacket. Adjustable belt for a comfortable fit, complete with shoulder pads and front zip pocket.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 80,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/leather-jacket-and-tea_925x_1d8c2479-ce1c-49ef-bf9f-f2efaa43024d.jpg?v=1692687774',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 36,
        country_origin: '',
    },
    {
        handle: 'striped-silk-blouse',
        title: 'Striped Silk Blouse',
        body: '<p>Ultra-stylish black and red striped silk blouse with buckle collar and matching button pants.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: false,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 50,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/striped-blouse-fashion_925x_6759a292-0373-49b8-a8fe-63b5c622f965.jpg?v=1692687772',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'archived',
        id: 37,
        country_origin: '',
    },
    {
        handle: 'floral-white-top',
        title: 'Floral White Top',
        body: '<p>Stylish sleeveless white top with a floral pattern.</p>',
        vendor: 'partners-demo',
        product_category: '',
        type: '',
        tags: ['women'],
        published: true,
        variant_title: 'title',
        'Option1 Value': 'Default title',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 75,
        compare_at_price: '',
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/city-woman-fashion_925x_2x_db1a18b1-0d8b-4435-b69f-dba73adbf4e5.jpg?v=1692687770',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img: '',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 38,
        country_origin: '',
    },
    {
        handle: 'chain-bracelet',
        title: '7 Shakra Bracelet',
        body: '<p>7 chakra bracelet, in blue or black.</p>',
        vendor: 'Company 123',
        product_category: '',
        type: 'Bracelet',
        tags: ['Beads'],
        published: true,
        variant_title: 'Color',
        'Option1 Value': 'Blue',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 1,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 42.99,
        compare_at_price: 44.99,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/7-chakra-bracelet_925x_ce5dfc1b-326c-49ed-9ca0-349c26433630.jpg?v=1692687622',
        'Image Position': 1,
        'Image Alt Text': '',
        'Gift Card': false,
        seo_title: '',
        seo_description: '',
        variant_img:
            'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/navy-blue-chakra-bracelet_925x_9db8e490-5f7a-4b1b-853d-66f50add65c6.jpg?v=1692687622',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: true,
        included_international: true,
        status: 'active',
        id: 39,
        country_origin: '',
    },
    {
        handle: 'chain-bracelet',
        title: '',
        body: '',
        vendor: '',
        product_category: '',
        type: '',
        tags: [],
        published: '',
        variant_title: 'Blue',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 0,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 42.99,
        compare_at_price: 44.99,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/navy-blue-chakra-bracelet_925x_9db8e490-5f7a-4b1b-853d-66f50add65c6.jpg?v=1692687622',
        'Image Position': 2,
        'Image Alt Text': '',
        'Gift Card': '',
        seo_title: '',
        seo_description: '',
        variant_img:
            'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/7-chakra-bracelet_925x_ce5dfc1b-326c-49ed-9ca0-349c26433630.jpg?v=1692687622',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: '',
        included_international: '',
        status: '',
        id: 40,
        country_origin: '',
    },
    {
        handle: 'chain-bracelet',
        title: '',
        body: '',
        vendor: '',
        product_category: '',
        type: '',
        tags: [],
        published: '',
        variant_title: 'Black',
        'Option2 Name': '',
        'Option2 Value': '',
        'Option3 Name': '',
        'Option3 Value': '',
        sku: '',
        weight_in_grams: 0,
        inventory_tracker: false,
        inventory_qty: 0,
        'Variant Inventory Policy': 'deny',
        'Variant Fulfillment Service': 'manual',
        base_price: 42.99,
        compare_at_price: 44.99,
        requires_shipping: true,
        is_taxable: true,
        barcode: '',
        img: 'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/navy-blue-chakra-bracelet_925x_9db8e490-5f7a-4b1b-853d-66f50add65c6.jpg?v=1692687622',
        'Image Position': 2,
        'Image Alt Text': '',
        'Gift Card': '',
        seo_title: '',
        seo_description: '',
        variant_img:
            'https://cdn.shopify.com/s/files/1/0813/1831/4302/products/7-chakra-bracelet_925x_ce5dfc1b-326c-49ed-9ca0-349c26433630.jpg?v=1692687622',
        weight_unit: 'kg',
        'Variant Tax Code': '',
        cost_per_item: 0,
        included_india: '',
        included_international: '',
        status: '',
        id: 41,
        country_origin: '',
    },
];

export const columnData = [
    { id: 0, name: 'Product title', key: 'title' },
    { id: 1, name: 'Tags', key: 'tags' },
    { id: 2, name: 'Status', key: 'status' },
    { id: 4, name: 'Product type', key: 'type' },
    { id: 5, name: 'Vendor', key: 'vendor' },
    { id: 6, name: 'Template', key: 'template' },
    { id: 7, name: 'Primary Market (India)', key: 'included_india' },
    { id: 8, name: 'International', key: 'included_international' },
    { id: 9, name: 'Base price', key: 'base_price' },
    { id: 10, name: 'Compare-at price', key: 'compare_at_price' },
    { id: 11, name: 'Cost per item', key: 'cost_per_item' },
    { id: 12, name: 'Charges taxes', key: 'is_taxable' },
    { id: 13, name: 'SKU', key: 'sku' },
    { id: 14, name: 'Barcode (ISBN, UPC, GTIN, etc.)', key: 'barcode' },
    { id: 15, name: 'Available quantity', key: 'inventory_qty' },
    { id: 16, name: 'Track quantity', key: 'inventory_tracker' },
    { id: 17, name: 'Weight', key: 'weight_in_grams' },
    { id: 18, name: 'Requires shipping', key: 'requires_shipping' },
    { id: 19, name: 'Country of origin', key: 'country_origin' },
    { id: 20, name: 'Page title (SEO)', key: 'seo_title' },
    { id: 21, name: 'Meta description (SEO)', key: 'seo_description' },
];

export const weightUnitOptions = [
    { label: 'lb', value: 'lb' },
    { label: 'oz', value: 'oz' },
    { label: 'kg', value: 'kg' },
    { label: 'g', value: 'g' },
];

export const countriesListOptions = [
    {
        label: 'Afghanistan',
        value: 'Afghanistan',
    },
    {
        label: 'Albania',
        value: 'Albania',
    },
    {
        label: 'Algeria',
        value: 'Algeria',
    },
    {
        label: 'American Samoa',
        value: 'American Samoa',
    },
    {
        label: 'Andorra',
        value: 'Andorra',
    },
    {
        label: 'Angola',
        value: 'Angola',
    },
    {
        label: 'Anguilla',
        value: 'Anguilla',
    },
    {
        label: 'Antarctica',
        value: 'Antarctica',
    },
    {
        label: 'Antigua and Barbuda',
        value: 'Antigua and Barbuda',
    },
    {
        label: 'Argentina',
        value: 'Argentina',
    },
    {
        label: 'Armenia',
        value: 'Armenia',
    },
    {
        label: 'Aruba',
        value: 'Aruba',
    },
    {
        label: 'Australia',
        value: 'Australia',
    },
    {
        label: 'Austria',
        value: 'Austria',
    },
    {
        label: 'Azerbaijan',
        value: 'Azerbaijan',
    },
    {
        label: 'Bahamas (the)',
        value: 'Bahamas (the)',
    },
    {
        label: 'Bahrain',
        value: 'Bahrain',
    },
    {
        label: 'Bangladesh',
        value: 'Bangladesh',
    },
    {
        label: 'Barbados',
        value: 'Barbados',
    },
    {
        label: 'Belarus',
        value: 'Belarus',
    },
    {
        label: 'Belgium',
        value: 'Belgium',
    },
    {
        label: 'Belize',
        value: 'Belize',
    },
    {
        label: 'Benin',
        value: 'Benin',
    },
    {
        label: 'Bermuda',
        value: 'Bermuda',
    },
    {
        label: 'Bhutan',
        value: 'Bhutan',
    },
    {
        label: 'Bolivia (Plurinational State of)',
        value: 'Bolivia (Plurinational State of)',
    },
    {
        label: 'Bonaire, Sint Eustatius and Saba',
        value: 'Bonaire, Sint Eustatius and Saba',
    },
    {
        label: 'Bosnia and Herzegovina',
        value: 'Bosnia and Herzegovina',
    },
    {
        label: 'Botswana',
        value: 'Botswana',
    },
    {
        label: 'Bouvet Island',
        value: 'Bouvet Island',
    },
    {
        label: 'Brazil',
        value: 'Brazil',
    },
    {
        label: 'British Indian Ocean Territory (the)',
        value: 'British Indian Ocean Territory (the)',
    },
    {
        label: 'Brunei Darussalam',
        value: 'Brunei Darussalam',
    },
    {
        label: 'Bulgaria',
        value: 'Bulgaria',
    },
    {
        label: 'Burkina Faso',
        value: 'Burkina Faso',
    },
    {
        label: 'Burundi',
        value: 'Burundi',
    },
    {
        label: 'Cabo Verde',
        value: 'Cabo Verde',
    },
    {
        label: 'Cambodia',
        value: 'Cambodia',
    },
    {
        label: 'Cameroon',
        value: 'Cameroon',
    },
    {
        label: 'Canada',
        value: 'Canada',
    },
    {
        label: 'Cayman Islands (the)',
        value: 'Cayman Islands (the)',
    },
    {
        label: 'Central African Republic (the)',
        value: 'Central African Republic (the)',
    },
    {
        label: 'Chad',
        value: 'Chad',
    },
    {
        label: 'Chile',
        value: 'Chile',
    },
    {
        label: 'China',
        value: 'China',
    },
    {
        label: 'Christmas Island',
        value: 'Christmas Island',
    },
    {
        label: 'Cocos (Keeling) Islands (the)',
        value: 'Cocos (Keeling) Islands (the)',
    },
    {
        label: 'Colombia',
        value: 'Colombia',
    },
    {
        label: 'Comoros (the)',
        value: 'Comoros (the)',
    },
    {
        label: 'Congo (the Democratic Republic of the)',
        value: 'Congo (the Democratic Republic of the)',
    },
    {
        label: 'Congo (the)',
        value: 'Congo (the)',
    },
    {
        label: 'Cook Islands (the)',
        value: 'Cook Islands (the)',
    },
    {
        label: 'Costa Rica',
        value: 'Costa Rica',
    },
    {
        label: 'Croatia',
        value: 'Croatia',
    },
    {
        label: 'Cuba',
        value: 'Cuba',
    },
    {
        label: 'Curaçao',
        value: 'Curaçao',
    },
    {
        label: 'Cyprus',
        value: 'Cyprus',
    },
    {
        label: 'Czechia',
        value: 'Czechia',
    },
    {
        label: "Côte d'Ivoire",
        value: "Côte d'Ivoire",
    },
    {
        label: 'Denmark',
        value: 'Denmark',
    },
    {
        label: 'Djibouti',
        value: 'Djibouti',
    },
    {
        label: 'Dominica',
        value: 'Dominica',
    },
    {
        label: 'Dominican Republic (the)',
        value: 'Dominican Republic (the)',
    },
    {
        label: 'Ecuador',
        value: 'Ecuador',
    },
    {
        label: 'Egypt',
        value: 'Egypt',
    },
    {
        label: 'El Salvador',
        value: 'El Salvador',
    },
    {
        label: 'Equatorial Guinea',
        value: 'Equatorial Guinea',
    },
    {
        label: 'Eritrea',
        value: 'Eritrea',
    },
    {
        label: 'Estonia',
        value: 'Estonia',
    },
    {
        label: 'Eswatini',
        value: 'Eswatini',
    },
    {
        label: 'Ethiopia',
        value: 'Ethiopia',
    },
    {
        label: 'Falkland Islands (the) [Malvinas]',
        value: 'Falkland Islands (the) [Malvinas]',
    },
    {
        label: 'Faroe Islands (the)',
        value: 'Faroe Islands (the)',
    },
    {
        label: 'Fiji',
        value: 'Fiji',
    },
    {
        label: 'Finland',
        value: 'Finland',
    },
    {
        label: 'France',
        value: 'France',
    },
    {
        label: 'French Guiana',
        value: 'French Guiana',
    },
    {
        label: 'French Polynesia',
        value: 'French Polynesia',
    },
    {
        label: 'French Southern Territories (the)',
        value: 'French Southern Territories (the)',
    },
    {
        label: 'Gabon',
        value: 'Gabon',
    },
    {
        label: 'Gambia (the)',
        value: 'Gambia (the)',
    },
    {
        label: 'Georgia',
        value: 'Georgia',
    },
    {
        label: 'Germany',
        value: 'Germany',
    },
    {
        label: 'Ghana',
        value: 'Ghana',
    },
    {
        label: 'Gibraltar',
        value: 'Gibraltar',
    },
    {
        label: 'Greece',
        value: 'Greece',
    },
    {
        label: 'Greenland',
        value: 'Greenland',
    },
    {
        label: 'Grenada',
        value: 'Grenada',
    },
    {
        label: 'Guadeloupe',
        value: 'Guadeloupe',
    },
    {
        label: 'Guam',
        value: 'Guam',
    },
    {
        label: 'Guatemala',
        value: 'Guatemala',
    },
    {
        label: 'Guernsey',
        value: 'Guernsey',
    },
    {
        label: 'Guinea',
        value: 'Guinea',
    },
    {
        label: 'Guinea-Bissau',
        value: 'Guinea-Bissau',
    },
    {
        label: 'Guyana',
        value: 'Guyana',
    },
    {
        label: 'Haiti',
        value: 'Haiti',
    },
    {
        label: 'Heard Island and McDonald Islands',
        value: 'Heard Island and McDonald Islands',
    },
    {
        label: 'Holy See (the)',
        value: 'Holy See (the)',
    },
    {
        label: 'Honduras',
        value: 'Honduras',
    },
    {
        label: 'Hong Kong',
        value: 'Hong Kong',
    },
    {
        label: 'Hungary',
        value: 'Hungary',
    },
    {
        label: 'Iceland',
        value: 'Iceland',
    },
    {
        label: 'India',
        value: 'India',
    },
    {
        label: 'Indonesia',
        value: 'Indonesia',
    },
    {
        label: 'Iran (Islamic Republic of)',
        value: 'Iran (Islamic Republic of)',
    },
    {
        label: 'Iraq',
        value: 'Iraq',
    },
    {
        label: 'Ireland',
        value: 'Ireland',
    },
    {
        label: 'Isle of Man',
        value: 'Isle of Man',
    },
    {
        label: 'Israel',
        value: 'Israel',
    },
    {
        label: 'Italy',
        value: 'Italy',
    },
    {
        label: 'Jamaica',
        value: 'Jamaica',
    },
    {
        label: 'Japan',
        value: 'Japan',
    },
    {
        label: 'Jersey',
        value: 'Jersey',
    },
    {
        label: 'Jordan',
        value: 'Jordan',
    },
    {
        label: 'Kazakhstan',
        value: 'Kazakhstan',
    },
    {
        label: 'Kenya',
        value: 'Kenya',
    },
    {
        label: 'Kiribati',
        value: 'Kiribati',
    },
    {
        label: "Korea (the Democratic People's Republic of)",
        value: "Korea (the Democratic People's Republic of)",
    },
    {
        label: 'Korea (the Republic of)',
        value: 'Korea (the Republic of)',
    },
    {
        label: 'Kuwait',
        value: 'Kuwait',
    },
    {
        label: 'Kyrgyzstan',
        value: 'Kyrgyzstan',
    },
    {
        label: "Lao People's Democratic Republic (the)",
        value: "Lao People's Democratic Republic (the)",
    },
    {
        label: 'Latvia',
        value: 'Latvia',
    },
    {
        label: 'Lebanon',
        value: 'Lebanon',
    },
    {
        label: 'Lesotho',
        value: 'Lesotho',
    },
    {
        label: 'Liberia',
        value: 'Liberia',
    },
    {
        label: 'Libya',
        value: 'Libya',
    },
    {
        label: 'Liechtenstein',
        value: 'Liechtenstein',
    },
    {
        label: 'Lithuania',
        value: 'Lithuania',
    },
    {
        label: 'Luxembourg',
        value: 'Luxembourg',
    },
    {
        label: 'Macao',
        value: 'Macao',
    },
    {
        label: 'Madagascar',
        value: 'Madagascar',
    },
    {
        label: 'Malawi',
        value: 'Malawi',
    },
    {
        label: 'Malaysia',
        value: 'Malaysia',
    },
    {
        label: 'Maldives',
        value: 'Maldives',
    },
    {
        label: 'Mali',
        value: 'Mali',
    },
    {
        label: 'Malta',
        value: 'Malta',
    },
    {
        label: 'Marshall Islands (the)',
        value: 'Marshall Islands (the)',
    },
    {
        label: 'Martinique',
        value: 'Martinique',
    },
    {
        label: 'Mauritania',
        value: 'Mauritania',
    },
    {
        label: 'Mauritius',
        value: 'Mauritius',
    },
    {
        label: 'Mayotte',
        value: 'Mayotte',
    },
    {
        label: 'Mexico',
        value: 'Mexico',
    },
    {
        label: 'Micronesia (Federated States of)',
        value: 'Micronesia (Federated States of)',
    },
    {
        label: 'Moldova (the Republic of)',
        value: 'Moldova (the Republic of)',
    },
    {
        label: 'Monaco',
        value: 'Monaco',
    },
    {
        label: 'Mongolia',
        value: 'Mongolia',
    },
    {
        label: 'Montenegro',
        value: 'Montenegro',
    },
    {
        label: 'Montserrat',
        value: 'Montserrat',
    },
    {
        label: 'Morocco',
        value: 'Morocco',
    },
    {
        label: 'Mozambique',
        value: 'Mozambique',
    },
    {
        label: 'Myanmar',
        value: 'Myanmar',
    },
    {
        label: 'Namibia',
        value: 'Namibia',
    },
    {
        label: 'Nauru',
        value: 'Nauru',
    },
    {
        label: 'Nepal',
        value: 'Nepal',
    },
    {
        label: 'Netherlands (the)',
        value: 'Netherlands (the)',
    },
    {
        label: 'New Caledonia',
        value: 'New Caledonia',
    },
    {
        label: 'New Zealand',
        value: 'New Zealand',
    },
    {
        label: 'Nicaragua',
        value: 'Nicaragua',
    },
    {
        label: 'Niger (the)',
        value: 'Niger (the)',
    },
    {
        label: 'Nigeria',
        value: 'Nigeria',
    },
    {
        label: 'Niue',
        value: 'Niue',
    },
    {
        label: 'Norfolk Island',
        value: 'Norfolk Island',
    },
    {
        label: 'Northern Mariana Islands (the)',
        value: 'Northern Mariana Islands (the)',
    },
    {
        label: 'Norway',
        value: 'Norway',
    },
    {
        label: 'Oman',
        value: 'Oman',
    },
    {
        label: 'Pakistan',
        value: 'Pakistan',
    },
    {
        label: 'Palau',
        value: 'Palau',
    },
    {
        label: 'Palestine, State of',
        value: 'Palestine, State of',
    },
    {
        label: 'Panama',
        value: 'Panama',
    },
    {
        label: 'Papua New Guinea',
        value: 'Papua New Guinea',
    },
    {
        label: 'Paraguay',
        value: 'Paraguay',
    },
    {
        label: 'Peru',
        value: 'Peru',
    },
    {
        label: 'Philippines (the)',
        value: 'Philippines (the)',
    },
    {
        label: 'Pitcairn',
        value: 'Pitcairn',
    },
    {
        label: 'Poland',
        value: 'Poland',
    },
    {
        label: 'Portugal',
        value: 'Portugal',
    },
    {
        label: 'Puerto Rico',
        value: 'Puerto Rico',
    },
    {
        label: 'Qatar',
        value: 'Qatar',
    },
    {
        label: 'Republic of North Macedonia',
        value: 'Republic of North Macedonia',
    },
    {
        label: 'Romania',
        value: 'Romania',
    },
    {
        label: 'Russian Federation (the)',
        value: 'Russian Federation (the)',
    },
    {
        label: 'Rwanda',
        value: 'Rwanda',
    },
    {
        label: 'Réunion',
        value: 'Réunion',
    },
    {
        label: 'Saint Barthélemy',
        value: 'Saint Barthélemy',
    },
    {
        label: 'Saint Helena, Ascension and Tristan da Cunha',
        value: 'Saint Helena, Ascension and Tristan da Cunha',
    },
    {
        label: 'Saint Kitts and Nevis',
        value: 'Saint Kitts and Nevis',
    },
    {
        label: 'Saint Lucia',
        value: 'Saint Lucia',
    },
    {
        label: 'Saint Martin (French part)',
        value: 'Saint Martin (French part)',
    },
    {
        label: 'Saint Pierre and Miquelon',
        value: 'Saint Pierre and Miquelon',
    },
    {
        label: 'Saint Vincent and the Grenadines',
        value: 'Saint Vincent and the Grenadines',
    },
    {
        label: 'Samoa',
        value: 'Samoa',
    },
    {
        label: 'San Marino',
        value: 'San Marino',
    },
    {
        label: 'Sao Tome and Principe',
        value: 'Sao Tome and Principe',
    },
    {
        label: 'Saudi Arabia',
        value: 'Saudi Arabia',
    },
    {
        label: 'Senegal',
        value: 'Senegal',
    },
    {
        label: 'Serbia',
        value: 'Serbia',
    },
    {
        label: 'Seychelles',
        value: 'Seychelles',
    },
    {
        label: 'Sierra Leone',
        value: 'Sierra Leone',
    },
    {
        label: 'Singapore',
        value: 'Singapore',
    },
    {
        label: 'Sint Maarten (Dutch part)',
        value: 'Sint Maarten (Dutch part)',
    },
    {
        label: 'Slovakia',
        value: 'Slovakia',
    },
    {
        label: 'Slovenia',
        value: 'Slovenia',
    },
    {
        label: 'Solomon Islands',
        value: 'Solomon Islands',
    },
    {
        label: 'Somalia',
        value: 'Somalia',
    },
    {
        label: 'South Africa',
        value: 'South Africa',
    },
    {
        label: 'South Georgia and the South Sandwich Islands',
        value: 'South Georgia and the South Sandwich Islands',
    },
    {
        label: 'South Sudan',
        value: 'South Sudan',
    },
    {
        label: 'Spain',
        value: 'Spain',
    },
    {
        label: 'Sri Lanka',
        value: 'Sri Lanka',
    },
    {
        label: 'Sudan (the)',
        value: 'Sudan (the)',
    },
    {
        label: 'Suriname',
        value: 'Suriname',
    },
    {
        label: 'Svalbard and Jan Mayen',
        value: 'Svalbard and Jan Mayen',
    },
    {
        label: 'Sweden',
        value: 'Sweden',
    },
    {
        label: 'Switzerland',
        value: 'Switzerland',
    },
    {
        label: 'Syrian Arab Republic',
        value: 'Syrian Arab Republic',
    },
    {
        label: 'Taiwan',
        value: 'Taiwan',
    },
    {
        label: 'Tajikistan',
        value: 'Tajikistan',
    },
    {
        label: 'Tanzania, United Republic of',
        value: 'Tanzania, United Republic of',
    },
    {
        label: 'Thailand',
        value: 'Thailand',
    },
    {
        label: 'Timor-Leste',
        value: 'Timor-Leste',
    },
    {
        label: 'Togo',
        value: 'Togo',
    },
    {
        label: 'Tokelau',
        value: 'Tokelau',
    },
    {
        label: 'Tonga',
        value: 'Tonga',
    },
    {
        label: 'Trinidad and Tobago',
        value: 'Trinidad and Tobago',
    },
    {
        label: 'Tunisia',
        value: 'Tunisia',
    },
    {
        label: 'Turkey',
        value: 'Turkey',
    },
    {
        label: 'Turkmenistan',
        value: 'Turkmenistan',
    },
    {
        label: 'Turks and Caicos Islands (the)',
        value: 'Turks and Caicos Islands (the)',
    },
    {
        label: 'Tuvalu',
        value: 'Tuvalu',
    },
    {
        label: 'Uganda',
        value: 'Uganda',
    },
    {
        label: 'Ukraine',
        value: 'Ukraine',
    },
    {
        label: 'United Arab Emirates (the)',
        value: 'United Arab Emirates (the)',
    },
    {
        label: 'United Kingdom of Great Britain and Northern Ireland (the)',
        value: 'United Kingdom of Great Britain and Northern Ireland (the)',
    },
    {
        label: 'United States Minor Outlying Islands (the)',
        value: 'United States Minor Outlying Islands (the)',
    },
    {
        label: 'United States of America (the)',
        value: 'United States of America (the)',
    },
    {
        label: 'Uruguay',
        value: 'Uruguay',
    },
    {
        label: 'Uzbekistan',
        value: 'Uzbekistan',
    },
    {
        label: 'Vanuatu',
        value: 'Vanuatu',
    },
    {
        label: 'Venezuela (Bolivarian Republic of)',
        value: 'Venezuela (Bolivarian Republic of)',
    },
    {
        label: 'Viet Nam',
        value: 'Viet Nam',
    },
    {
        label: 'Virgin Islands (British)',
        value: 'Virgin Islands (British)',
    },
    {
        label: 'Virgin Islands (U.S.)',
        value: 'Virgin Islands (U.S.)',
    },
    {
        label: 'Wallis and Futuna',
        value: 'Wallis and Futuna',
    },
    {
        label: 'Western Sahara',
        value: 'Western Sahara',
    },
    {
        label: 'Yemen',
        value: 'Yemen',
    },
    {
        label: 'Zambia',
        value: 'Zambia',
    },
    {
        label: 'Zimbabwe',
        value: 'Zimbabwe',
    },
    {
        label: 'Åland Islands',
        value: 'Åland Islands',
    },
];

export const productTypesOptions = [
    { label: 'Indoor', value: 'Indoor' },
    { label: 'Outdoor', value: 'Outdoor' },
    { label: 'Necklace', value: 'Necklace' },
    { label: 'Bracelet', value: 'Bracelet' },
    { label: 'Earrings', value: 'Earrings' },
];

export const vendorOptions = [
    { label: 'Company 123', value: 'Company 123' },
    { label: 'Home Sweet Home', value: 'Home Sweet Home' },
    { label: 'Rustic LTD', value: 'Rustic LTD' },
    { label: 'partners-demo', value: 'partners-demo' },
    { label: 'Sterling Ltd', value: 'Sterling Ltd' },
];

export const statusOptions = [
    { value: 'active', label: 'Active' },
    { value: 'archived', label: 'Archived' },
    { value: 'draft', label: 'Draft' },
];

export const tagOptions = [
    {
        label: 'Bedroom',
        value: 'Bedroom',
    },
    {
        label: 'Wood',
        value: 'Wood',
    },
    {
        label: 'Black',
        value: 'Black',
    },
    {
        label: 'Leather',
        value: 'Leather',
    },
    {
        label: 'Candle',
        value: 'Candle',
    },
    {
        label: 'Pillows',
        value: 'Pillows',
    },
    {
        label: 'Sofa',
        value: 'Sofa',
    },
    {
        label: 'Garden',
        value: 'Garden',
    },
    {
        label: 'Plants',
        value: 'Plants',
    },
    {
        label: 'Pot',
        value: 'Pot',
    },
    {
        label: 'Chair',
        value: 'Chair',
    },
    {
        label: 'Bed',
        value: 'Bed',
    },
    {
        label: 'Antique',
        value: 'Antique',
    },
    {
        label: 'Couch',
        value: 'Couch',
    },
    {
        label: 'Copper',
        value: 'Copper',
    },
    {
        label: 'men',
        value: 'men',
    },
    {
        label: 'women',
        value: 'women',
    },
    {
        label: 'Gold',
        value: 'Gold',
    },
    {
        label: 'Turquoise',
        value: 'Turquoise',
    },
    {
        label: 'Silver',
        value: 'Silver',
    },
    {
        label: 'Crane',
        value: 'Crane',
    },
    {
        label: 'Origami',
        value: 'Origami',
    },
    {
        label: 'Moon',
        value: 'Moon',
    },
    {
        label: 'Angel',
        value: 'Angel',
    },
    {
        label: 'Bird',
        value: 'Bird',
    },
    {
        label: 'Blue',
        value: 'Blue',
    },
    {
        label: 'Gem',
        value: 'Gem',
    },
    {
        label: 'Purple',
        value: 'Purple',
    },
    {
        label: 'Galaxy',
        value: 'Galaxy',
    },
    {
        label: 'Dreamcatcher',
        value: 'Dreamcatcher',
    },
    {
        label: 'Pendant',
        value: 'Pendant',
    },
    {
        label: 'Triangle',
        value: 'Triangle',
    },
    {
        label: 'Choker',
        value: 'Choker',
    },
    {
        label: 'Diamond',
        value: 'Diamond',
    },
    {
        label: 'Anchor',
        value: 'Anchor',
    },
    {
        label: 'Beads',
        value: 'Beads',
    },
];
